fix: handle 0-sized logits
Problem:
`min_tokens` sampling param is broken due to empty logit from partial
prefill.
```
File "vllm_rbln/v1/worker/rbln_model_runner.py", line 2611, in sample_tokens
  sampler_output = self._sample(logits, spec_decode_metadata)
File "vllm_rbln/v1/worker/rbln_model_runner.py", line 1604, in _sample
  sampler_output = self.sampler(
...
File "vllm/v1/sample/sampler.py", line 92, in forward
  logits = self.apply_logits_processors(
File "vllm/v1/sample/sampler.py", line 296, in apply_logits_processors
  logits = processor.apply(logits)
File "vllm/v1/sample/logits_processor/builtin.py", line 236, in apply
  logits.index_put_(self.logits_slice, self.neg_inf_tensor)
IndexError: index is out of bounds for dimension with size 0
```
A similar issue happens to device sampler.

Solution:
Skip logit processor for that case.